version: "3.1"

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MF_POSTGRES_DB: ${MF_POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  
  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile.monolithfood
    environment:
      MF_SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/${MF_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Perfil de Spring
      SPRING_PROFILES_ACTIVE: prod
      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # JWT
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXP_TIME: ${JWT_EXP_TIME}
      # Oauth2
      OAUTH2_GITHUB_CLIENT_ID: ${OAUTH2_GITHUB_CLIENT_ID}
      OAUTH2_GITHUB_CLIENT_SECRET: ${OAUTH2_GITHUB_CLIENT_SECRET}
      OAUTH2_GOOGLE_CLIENT_ID: ${OAUTH2_GOOGLE_CLIENT_ID}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      OAUTH2_MICROSOFT_CLIENT_ID: ${OAUTH2_MICROSOFT_CLIENT_ID}
      OAUTH2_MICROSOFT_CLIENT_SECRET: ${OAUTH2_MICROSOFT_CLIENT_SECRET}
    depends_on:
      - postgresdb
      - redis
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springbootapp

volumes:
  postgres:
